apiVersion: v2
name: infra-cache
description: Caching layer using Redis HA (Sentinel) & Redis Exporter
type: application
version: 0.1.0
appVersion: "7.4"

dependencies:
  - name: redis
    version: 20.4.2
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: prometheus-redis-exporter
    version: 6.5.1
    repository: https://prometheus-community.github.io/helm-charts
