---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-store-minio
  namespace: fineract
spec:
  encryptedData:
    root-password: AgBimR7RdMebAmifQwPv9Ws6+4XFjOaxMxy/3O3AEDxMqiWg9fVnl2TsG43mWmhYMeIu5cFdqFlzM5PTQu08dI/sslmG+7msZzVwZ03GGBen4PucvqcJWHiwqjnkORvDB1XLzsvDc5vZEf9rewGXLB36TSMmSove6l8+BZGiF/tjV6IjERvptmKoixuoNicH6hCVD2ZiMh9ZaFho/6nEtdEVC4uG4vjSDeFGPbWRmY+Gsy3hQDMPPbsCQGt314tP20qISHkr+CwnWMobalpYseM1pnfgMqPmLmsgMb17Q3Zx044k2vf8twhplqk9sIO0xNRxRLNG2byvBulWl8dJkKThdl4Y76gVb+yekUORP0jhZ7J1V5/Y3ra95xd0x4sxrv0rIXR/A/uq444wKcwbGQAPYVI/ACFwhbX3TdaaIaXyEeakPIIMvQDhYJd0Orcrq5S4V1Pf3eA/4XXidPvpomN34nFZ7lsTXeMzgjx2NpbrhW3U7miv/nnioJl01qrQIV/qH6H0cgaSlyQGMB+UYkp/tLpwcBHZ0kMJ8QbTeJwbGY3Vz4MLexcjO5xkiCZvEd0XUFYl4jbkaigJg0Jo1mNcej2JMfDUDwl4GWFY3HuAJU0toa27TautlHw+DecixyD+p/6YzevYQiEBhV+a0hHmViBVG+lOWmy98+wqsj65SWN8gtOlcICvLJ0XKk4lau2inm9SG41WKq37aRmQkQ==
    root-user: AgAv6+4e+mLjb64QXJiIaQJS9e3bC8mlXx2Cl14J74u05/EvbLu1C1XVnDlM+q5YoUe72IyZXpRvHtdvsn88E43e8/06jf11uyKu8gkGhcGFCpmagB0q93uEt5bEisDybshbTA3LbihB0g0YL1o3CJMQeZKy/ut9v3mx7Z3TH/lCyT8BGJvleDduDPsRXfmaA/9Ys6OEkOt6qQVxeMI3Zy28XLTDOtseXIxrQY/2gxmGJFoFNJ23rPhI5gQ5lyFdcb9QK8YeUa4lslyM/WBq+fonHc5RLYl5k00yKJnLQYNn0/hISRLU/r5U4Vx70UQNoskmJf1PkA1eYqLqBXP4L74x0X3dFRkbnEsozXEhbDiHB2C6cPzI7q22MCRVYRwlCtS6ycpn+ROjBQcZcpiqXPXWM5902krtkqjdCpLInbNbdgtTp8tu6WCWyKBqdklGVvwWxoByADjrKhLaIgqCOkzNh3qsvTbFdIk8QE6uQqib14coEdc3Av49ySy+fNGgEiQMs4VjSoGGEXz4+2/tMgIbV2baUOTGpwyPW0ILCx19OkQeQUCz8fVA5lEwM8rZNuO9lejPt8pQD9XiChTTww1WW5E0JhY+rnqsFM5hkvQb6Uam11gb+is/YknNLnpfL0O4OzPRQHJDJdlV4UCEC10Q89TzcSZFkNxCFb/6b1eboPpBHhEm/ClUKo15TB5MD5D8KCSblcbl85B9
  template:
    metadata:
      name: data-store-minio
      namespace: fineract
    type: Opaque
