---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-store-minio
  namespace: data-store
spec:
  encryptedData:
    root-password: AgBvso2+FMxFIF+jgk1HzPUkp8HJCX5bLwB8KlXpCDoc4hJAhjL4PIA3tGkpQ0aMvDHfV98tvya/A4hfSA2JAk6RRsMDRxGcfGihZ+utcn9ZR3OnJZV77LkBA/kGx2OTrwkeE7ciMBHiC9nc1oiol/xP3cHCX8tDPDqOVJYeZTcqmHpOUPqtOGm5e9e2fM6b80QFBcpDTPOYChh5Drg7UW+BGgu3QrEzPckRJWsJhjtW+dklcihbkGcnpAg1qsxuyE7bAa92WM+L03nege0UqgJBPgDc5dzmgV+Ac6bcYpcfqhH/+o+ObBleSje9W7KJjRyJEHGEc75ItOIgHBeuoZXroarOIhtiy+hctTOsM5XEs5F8jcN5CGE12vszKLMKbqBQs4uRJ+CG52d1hsTe14du2WRVlfieMKWLe8mWoTIY9ls+zv6DmG9WYHy2JXdHUPRTKSUYKjrrsie/HXqpDJEK5NPHLFhyJeamVnVziz7Ixk4lsJHwJ76CImQO/66P44T4sQnaoHdmYfCJc7OvP9gTQFCqSjQ6Zr41E8pT6wuboGSmUFTs8pL/10GF20XeEI2ULhvAsgxMsRYvtWRelLKSFkSH6x2lZFHc/Prgn6/yZfnORjVliiJVvP2Xli/SuZbhozWcdbLbZpr86tKwFdeuBW1bS9Xnu3Jgkp4OwJWJK79pqQOtPwUj851nP8UnhbmHXiUvT+GvxuFeI2vzol86
    root-user: AgArCleuCn4/s4H3kZGNPlqn+6mYBDq/2Qy1fWAc+E0ZL6MbXaX+IUc8Tu+lseMFYK79yUHVq6NQECOTVBsmnEHz2WQqcMWxJ0g7dpxoBF3Hiuzi+Qzi4YWsdvaBy1bKNPewuhXzsThvnko0kX10gkSDbEMOz1xIrrJfhmtRe+l1gQecT+uKOiyROj4VRRHFmfQP9f7zOYfJb8kcueHolDYv/CCxcIkLshRGRS2KtCjYBknutOaJihsIuHfLN+Lki4J/zFNskldyYTo5AlQ0FN88BOHQXlEk8Nht315KjuDXhH0L8rOEGADCGY//Y7wBG1GXge1N51Bc0RubBHrhN0CnwRwyU0ZvTBmTY3PKCwl4XyzxS3qXZetWM32enGh9tMsq699H5f+ELk7B5+1OZZBnsAvvYTIVtVgSmdRYkop6KoRmftNq8penHm/48pK1U78GkGPQQ5ZSCnCt5aiG3NmdvHAVJ26gddUteLxbSVVnxjDgHf3ojBiiaLwiBP9uVgY551OyqlR4rAqtJ1ZfWy0rk96IOlI+DjBdrlbZvMvIHde4vX2OKEY/YiiRFSi/sv3+XqZ5B91yfuF+5OxenSTf0eneZykeMQOC49eIhjGKudvqpnR36S1B0mOaW07Krjh8WStTfcDS8WkgZs4duEgDJQFAKg+XYvYRBQCrpGf8bwy7r2b7rJDjoJsuGVfsB6nm8gSTJBYXo3YR
  template:
    metadata:
      name: data-store-minio
      namespace: data-store
    type: Opaque
