---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: asset-service-credentials
  namespace: fineract
spec:
  encryptedData:
    keycloak-client-secret: AgAofVZldmm3hhlkH8lDJCfytxX8M5UCHHjeoaU4ybcw9eU8/W8S+iVuFR8pBZd+kr1AVYyg1cFkPGuq3JmJX78Je6mD7PQjoJOll8L2Ixj33Fm6QEoH0pw5/r8QAzLyWnU/fLUqiTsglNru5mBvKuVIGXcYF+ChimhW9KMjpRMmQ14bkhNkPoh/FjnEb+sjzud68+iaX21z4OG6e7E0vcUJNC+fulZsEP4KgAlsgMXOh3aimYzpRSkwKlsp2gOCM5o9TLK4erolbdwIojIu17ZJjZIQEn/Rmx2g/D7soWR93iRLhc7AbGXIlZYlWGg/l9rsRYt7nf3tenQi2fCe8Usy6GQlAfkqK678XWnTcmx5907p2ILeomSgVg77jeHzDPTEN6zCPpIFIw3MR7rLESIgzqRPhx24ieK+4DUXg3sTaZG8cM38atw/w6Um3wJlmLALx/NjrD9YCjDjHUSr9J6se8q6p7nB2WEzDMQP6NNyki9v8xE2CPEMANeuyY0hn/0tKbB0qc8HFak2U+14XSTX/a0wucxELGJsZ/ztGLBbWgyzsmK8yipUc+Q6EaIHhCyy8MUL8YE9zHSoEwD8us1ikxC0vs7ICIC/CjC+9lb+ZHDjpvHx+vi1rqGtQpPgwEyTEvsTMgda+6eOFtdwZeScPXhP3m1wqwHFSesHK8661o28tjPxlE5kBpv6FncSa+9RmURBvM9pz2RUQnNraOGariTUIA==
  template:
    metadata:
      creationTimestamp: null
      name: asset-service-credentials
      namespace: fineract
