---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: customer-self-service-credentials
  namespace: fineract
spec:
  encryptedData:
    keycloak-client-secret: AgBwoOHRlJk+qMdterWJUYmDBE5/VBLpSV1shnH3TW5fHEuTMkb/aTOHXlPDaQ8J/4tQV3yJA3gEJc01Li+yR98PrxAoqB0p90kHmJKyXrb+XF81EsMMytaUR5iB9a38x+lLfD0zvr9biYWcEyfd4LZLvTEpblrwtcTf7zX8h+bHerBRjPY2M8yeURIq/ImxylhcNvaq8hhr+QF9JZj29Htvbad4vx08ldc61ZTQ5hlpS0+tP5Nib8RWXuuB1ebBg+XDfImhj1yLuQ6szBTd7udq9ucij4dHZyDz0lwoLQj8MOCrvdij/6Ze6DkOjEoMo9Qpj6nsY1FRL3lxwXDj0rWaO5F5P9dtdI0lF1VmrMWTb1DQqOCNGrYnY+pGrR7W3yHlnmwCas0VOPdaVWVNqU3YegjeO57kogMAJhN/c7iVNVZxx9nhiqB+n5MVfVukhUvmQ5ox1drFz0NRqo06T5EVpupo/j9B0nmtV9y9x2aWK3DlBK+yXqCfGv0o9aEGxNQcW6QtdrqZniH/ZuTYkBsjMSJMg6ROhP2Mje60KHFyPITDfCVh+G6i4nJ6JcG0z5CjoQyShSFmDyC9fAp3wDzCm33Y67/2uVCCMGMvAQIy0+q/CIk9DkX8SoJADixpih1q8bTLzVib8IpjvAm3cH77eu1NtDTviXIdc64jSxb2TA/nWDA3JfopTlRhjFJPcm8FZ8G+RLT0F6yXfPfzY3cCdI+Cy3io/zBD2biS
  template:
    metadata:
      creationTimestamp: null
      name: customer-self-service-credentials
      namespace: fineract
