---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: data-store-minio
  namespace: fineract
spec:
  encryptedData:
    root-password: AgAlzMmDzlnfD06U2xSDXxneniG+XNJx56cAubBYq2AmSbmxQ6cgKhJ20H2M4WwojGF6II+6wvLE80kXQnTIlIVDwxH31J4t9Jsk+/xeysM7fuIqqUuU60S2qscZgyc1TcmpGPmgirQzriVIGOnHsjxfGoBQHQ9LRjsv++gf9jUH9OyYCtKGogbvOInmgmOIUHSh4eUx1IX0O7MW6lF0UEMPhWCJ3Qdg8qsNo6uXUdMxBQw8hePRKPFYbhbrp9p1fUYmw94yLMDCcmZe+b6uPT7duBVQfPS6fleR/0KoaGqpyFYYuTy+aBnr8HNuV4nzOWaiZrxNUIOv8Wy+hSpTwM+B2FQiQx7AozhowVRda/hQbcy7UE7ktsqPL0cKaSlTv4jK9N3OM1GQd8FBm4mNrpPjQQnt61Yn4wKMNJhlMDyziix0PHfEQg1iGKktyOO+Kqga9/TgrQaMDmHES+V0uN0zDlmLylJHN4ozlj3M9r6So+TSIQtyiiuw5VDuMw1UDDmGq917EiKAMt+hHjC2wFtU55miyV8sfJrGtu9B2IysHKMCGr+xWisC+T57cie3Ttesvek5mr3oBILmITjRPaNQDLyR+3Sx59zOJlW/JCUjAlfYGzjAWdbGS/nYAsKdY1JrQpVuCOA7J/MZg/A7RvUVtxWj8jHft6i5B5WxdbDiPdMYCKylZoNaLSBkfdmswO5XBde1bpBUgPdUxXt7RAIkQabRTBNK7e1vYhtyceAJVyzo4NWjO5uv30A=
    root-user: AgBwh5rEUGZDwwTm58RzZgixT2FaUFnO7uuiLeW71GZ2RIjQWRW2pEfZ1Pyiu8eyljDpzdGck7nY40RDBdo/zt6KJtuFSHQNc5qTn4GydXyJsFp86e8zKRE9ADjSBz9SVGofVIOzH2SgmzNkvdNlbbAGpKRND/7hJ/dHqxHdeCy3bb/5UZ5PP5qjnX1zUyt6tdeudo4GfboYLEsIrgZUR6o8ufhOp7Y1EGfJyvER1ChRyatszoIsBEN5nl9HXqL5gqwaNp0fL49LVaMUSKnPqOA+oHIem/ylN4MweCvYQbCAzEnpcykheYQ/d20JXOiRcwh3sz0saNeNpmBowwJ2DvR/xueR1ahNg61dFz0c12pnR1FiVWC8E3bhpDZO7uIEuz0357VsrJcmC89cYzXPg35KVN7m+n7xV3RGNzw0A3ks7IGJi3rv3JIDkA9Y+OWHcUJuVb/1xHZ90KKDH3pa7qXTdCyk7x8XZPfiSPcyiPcHhgyV+aytx6cMAdU393tqkwCVj4r1a9DzncbDMWH58ngJKC0cA5yrk4xPRAXwXjNvBX3PMXzgtFUmpr36JRhuE/lJy/VIv30Bm3qQVSODTSFLLuPMP8jA0w8Za1IHI6G6rU904vtLiSEXkYUKDt69KDAMc6n3o2V3riiN+M02zj4/yc+VyoAYJLHOfddmZvRrU0tUARgMXZRgqFs9L1q5vyWBuktOA9P6Pfx2
  template:
    metadata:
      name: data-store-minio
      namespace: fineract
