apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-admin-credentials
  namespace: fineract
spec:
  encryptedData:
    password: AgDLJXi9h8Q9Xos9s3CyUZDD2qk/I3k0SagswYMWEHn/OqVTnLd5o6zj6QQ8LR21MsEJ70sDuUyvqriyH0qpWdoJhq7iKnJjl1JMLl2TuAn8K8PYsdaxl/XJf6yu1Aq/00OXB3wTz/F3ySG+Ic0f0JxyJ/1SO0liSJunJJcPdGIUhSb9clVTGeiWIk9xoJox+5zbLvXIJxxhgFD9UQ2FkSmKH6jXyNZxJdDUGHM2ctneb7Ub2vzVycEx/DbmiMZUCf8Gd9VXwAfpeIGiz+CpN3hfjeSIuAURD9scTdfjbeKgzaqY3Q2lHExlbWct4q78uyQOAXCXbJypLXyq/6tjfM6hP7Vm/gNJUViL0FZ6lle61JJYTTFNBWhXwJXgtiR6c+dGLZtc7lwGBX6xbMonELkgUbyf8AXALhHwzX8bxJDBf0rF+4jEBWUa8nr3eZHr0uEiexIcs8KboJEqv6cB3WyzLjl5kz5wIe+JV6QkzOXZB3y1ut6W0UjTzshNI+qlNPtrWHdssyU3lDtSzKc9V5xEjgoWoT8DjpbonH9THtZZdHWDSXIFa8phEDnpBhyPGXjH2QvQV7/KzDDBctapYeG90lqbpVijGKYFTaff5xInfpKy2xh8W1yR4YE2XFtY4pDJY1BSqVqGMjYyycIVIjncw9IDLaubYxZ4IfGdSXz8ADu/J8gPJ7NJsHXl1qDyYcrPnRqut9Eb/Bxd5HYkh00KeH+K2yJ41g==
    username: AgAD1kaK2ELAaNrr6af1/P8BMf0gsTesJ3DwQ8HihAnUlHl3DKV7BtzaS49uZCC5o+ay1doTELlJHFCO6JUsEP9IVdk3mMaYxu5n5CDtaqAJrZbIfCHriJPSWeHGURoQNDn4tzuBOy2CoBW/tYATvYojlbv1ST02rDyHq7B8zJOLQMXICby1Up04s9hbcy/hOHHXoLTkVFdsNCyQezA6+ZPFniOkIyet8HpBYZZH04YewZwlytD0g7f5m2xomXTvQTuq6ZrrPxtSeRc7B530OlRXYkQZdiDhtpg9oXWdjA/g/EjJXgQ8JdLNfS2dCG7AjUFQuH25cv5XMVlXOoldCjhS8i4ofz7BPGiSJi+mdIEDkZb4Y9cYdebAgCM16yRenOMp+5WB9gYEy7LQID412/RBseXJaRjDfjKuodVELtvRmiowTPinhA/W8ez0K+k5nS1ozVkYbid8MS/KqqtHQiqLvCtJPwwNjqPjUv2/cJ0M93tM3RbwP3UOWJvSJg9/JrTIod8cAq0c2581ORGT+UAkNWrOAW2B/L7LXYR/yhvexSO7WSUnnQYfUNROq0S9SLXopGVymYAjxSMnAOn0j/uMK6r5+es6uOkPtBaF9An0qZ/NnpjMlE815WBHuJV8UrwfDeYT1xA9vxm4Wx9cppcasqMRIGEMpx5qtpzkulEQAPcqZbWX23h4hYrKmBiN4c/Ub+fV3yTuVQ==
  template:
    metadata:
      name: db-admin-credentials
      namespace: fineract
    type: kubernetes.io/basic-auth
