---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: fineract
spec:
  encryptedData:
    .dockerconfigjson: AgAoYGnCICaUBEE8L3fLWgL2FLSkDL90w5Ds6CrSw+elLWwad7K0mIlnmazR+A4laluabXJBOlJ5sbXnG4GaK5IDeoURS6x0gXS3SrFxO5vRfy0KWYcxDorT9HeHiTp/E13gNrTb3BNKkEluicisF+sLvl6NKAfQxqK1iZUb3toz09EiLIDyRnlF/j93y+N3x9SYCbqeXB1/QbPiNTMADwsxyqmDw8Khdq8rrYvS5yYMA4y1JV4bFI5FLNDUwRD5bA562Q9NlA58tfcK3jM16/De0kAcgCiyG+1Xn/tIDONdr5XEnoh0GUxOQ5l2GE4t+g+P+rl3J8uYCFlr4fisEUI3jd73tXNo9SCdklkiVjdNrMEbHyKlch8er8rI6zbRjUMI4lKn8Tdz/cPtX8ZvQN8QEk9YwwXpa8EMqDSke4sM9NeFrfS4usOZSQVd3iM4zZ9EW7LRTN+9whSvN1vjhy9UhFj0a6h4qXoEKCmSmjsmH6OPv61uD+5WqKW4XLnnIiVnX5a24WAjfa/kH0n7QBwo9GsV4mxzNA9ZdQdXHm2YqKSuPxggJJnfZe4aBpT6jUZkWepSO/iyRv0ga67AGjb7LZ0syWB1Tt5npOPtg0jVoJcf/1Bos5eRsBm4vikTOubTqmpSRbr3oyh/32pbDfnDZrZ0YwgFkuZ5T9npxGjYxvcY183ZI8kQ4tbT71XZBLiFrd9Pdam428gKU26NLKkckUme0gMnhING4Aw5uKv7tN9cxfVW7fdjOk5/3EEoHGgDEtzTSif//SF6Qr3TBT6KMF13Z6tqFgD0zOTPQfU9ZtWTtZX/WV/GtkMHQolx4+lflfPaaBE77QCCIgT8V2Jdieark5dH8CE8Vx7Cr5QqKm64e+MjpblW2wqOiLSmy4rAKNJpePlUCLEipOOFCdPOoP0NW0w/MmZ2xIUK6EfjQ2w=
  template:
    metadata:
      name: ghcr-credentials
      namespace: fineract
    type: kubernetes.io/dockerconfigjson
