---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-keycloak
  namespace: fineract
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgC1BdgZaKSB3FpF/4FFa7QXlpRa3oYZ5r0UQUMs7LHzfR7hT1CHwbdvdi0IR0O9/A2qERaeaKA3Y1m98TPSq1d0cTzL2Epm141HLYt7TgJnRT/2rHm30D49JvLRalolzOFcK+k892EGx1VENpMyx5vYGuz31P/1E1oz45XgSdCr9EM2740rUF2r9z6t6w3i2Ph3xOiIEHy3lQkL/LhtNjK6va5so3r5xLn/Z+i1Hk5oMI+M7xM3xvTyGUg3+WVRqDRpJNydnEotKGWjuPHqfV+xs7eoTHdNfzdl6o+JQZ7gPet8/WsJBVpR5zxfFAi3kYJQaW8v7Mu/rUtQxA6CVVE/Kn8WKk5qw0ea7bni/SmkbMgFxjP04v2E7H6F922CxiKoOflvyNGrUTK5LL2BMFbkzdZp086s919zwLMeRuFZB/vXqj3Pxio8rk/Tn41B2YyuntFpqlygVuzgMiJFHYzACf1g//aZ8AbrgqijlnkPQvjoOUylXO0BrfLWWp/q5p0RkvbV2gQIIneUSWJdal485ZZGun4UN8eGghLnQR4PSB6WMg/W93zvsDaxFqnkrBKXdD1/1MLYKFJz9NA/ZGQ0Fe1J3zFEJyquI2POPDoJYot4nVN3OmbE4og4yjR163nOfl7wOEvnk3a/n4sJ5eKsFUu1JVUier/pchi5awcxFbTJPK/2y0y9zvv40wr0Xa2TYMDF0A==
    KEYCLOAK_ADMIN_PASSWORD: AgDCKI5cr1UdnwFjsvglnidoiNew8dJULeGsExidmh4HGrz3jdFrJi71TYM1KoAVk5PkspxkxDMPyGN0IT4nh9WSKCZDtKCnHxqrGykRgHzM8a67XADPrRZ/+VxZDiR/J7+t11JeB+kZY9nwzovD3vUtnMhQVU4bRZM9dMCeMbShFL4cSZ5ck89OyF5lWT4nIBWF9NeZPKRjB67+sMqOARHrA3QIXIHFq4tx6LB8RTHU4B7wx754FyNchhHZPHRwr9Py7IzEWD8Ev5mZXZ4au8PMRykKSiVM4bNXDkGqj069VpadGtRxLg6KzUvazsOvOEfj6fHUzOAHlC9LGX7CQ/CEFg4ZnxNfuYlJqCsABeEd+yFdMsGtl1c7qtqQ9W+yKXas0Ny4icsszpV86BG6FIagfN1ORzoKiaFH2nJ21gsdD3GD60CwSryyNZzdmNVRV25JmJD/SpuoTtP5IcuXDJxACOupBje+E+qLGilcIqjG3BElVs3xVPg41miN9js54XxY/RpLJe9MlGCwMZnKTnktW2gTA+ikT4mDv6FXZyeOh8dsMzkxLL8lBPbyrVaXd0fMumxFxMR0ktPVbTTfbHizKuTNTvLfvM8y8LKFBDirtuSUQl/dIkQ83/gd/aFncUdYba+SIHA8dWiAA+OES2X/sQWpqd1vI3a/MsT5yEN2uJdA4KLZQijmpm8t5CE4NVWkFmv68/yPMg==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-keycloak
      namespace: fineract
