---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres
  namespace: fineract
spec:
  encryptedData:
    KEYCLOAK_DB_PASSWORD: AgC3yNmB8YqYgKtBpUyfo+z5oSYYAfwUX36FILtPuvQ5MxO6twQdabEWn6smEOhC+DFwr2QmdmdsespPF1LgF4d/zp3X7Ebj70i5n27Wo5/mzUrrolV5No1vAqcF03saBXj5cwWbJCSpRwMkSlrlhQKrygc4FR5kvSRSNoxZm9EM7/alcEWkF+b9hnYQICymL+e+f1+0nl2fSuPOuFW10mUy58yhRsSpwQzUVU2qNCEE3gNd+5b1OYYOz/f9BgbjVD00K7UKMbSSr2jpkZWXruucqKaGQ22OYsgTKfFpj1FxPqPiuA+QbhMwHZ7ig4IyZQM+25W9IiQXbKlBCyiSM+dA1eHmqBv0AuzP6vn4R+flL+30FVCdXVnmf7kJwouLwRtmAAsR0qOLAvb6H7OicrArvrrGfX0SWrlJ/YeW/s3iDCdGkKBWHC5sZoJBsI/BAPHUjJtSepNQgn2UVG8/mLj0mT4AFgaJibNBmz+d3/IkekBDa/RmhyxB0vrLtftGUUWM4qKjWaLJZ5CDvtAKqqIAMusUTWDmP3IjJlaaC6sVx9ATQBOl0AxulXl0mJt/ZM+ckfco8CgEqhRXdlmPJ0AfCuShmWppK0StSC2ayNrIkPDEAFdfz6OdAw/MAVwVLWU+EbsTNMOBrIoysU93d9K5IhUj6hP04lwdQfOtQfDGQMAQ/S0XDQwIi1ARiP8pvqnkWwRc7QG50a7B+XtgKplWaw==
    KEYCLOAK_DB_USER: AgBbPiYJig6Tqm/XxE2rOF+g6UU9T1HwsGZXO1dw179FSGvSUl85FCsIEfJ+CD7/mHQDOTIZRqImbPi2LO+Q5HzyK5UZNpHVjgR3E4TJ/u/FDoaNhNu4S42o90ZwcPI3dPKwgdTur3NwPVbGJTTIQQPDApCYn5aNMGwnfyTN7HqzQnkxIpNOgieEjkz3sRc7zZMgGZQQZOnq+7m8A5WS1i+lsAltxi/kDC/mYylMxDCgt7Z7vdNi0Zdh+1vLTzwPfCuKAMI8srwjJBBsa2FpGVApWhS1/P1rKH/3lt89M3MkhST7UZPCfg2L4f4rGarjIoag3NkTULv/iNxRCx2lASR4NZHwq49YkkEIgVdFKkVTlXRg7q1FsAZO3AwPK6AInp92NfFR/ORgovstZxgbYoStA9a4OrO86frWXVrJJYp25h22OuLavyTKC6u+Ch2uxHTdppLhzbDk3jNlUQ+RLzcmfW4DReG0p5E9Dtw5W74LsPhD1XmplgwkOmUVI03DnE1k6QP/6NHyQu/lyaNx5vfeC/BT6/+UMifXr8NuHpiYNOJx2/zRAfJyIWpO/6OEZHuVl3DYaG63JbkFEjDAbvynpAwyj7Qxw6j7qtT+hPMZuTr0ZLzovJ3dwuWFJqHIEebWoCiKU75YlNgrIuZGrbtjZhKWNVNofq523uZgM48NVZpOh5T4sG98kWpkxp0lgyoUQ6PVEScY3Q==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres
      namespace: fineract
