---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kyc-manager-credentials
  namespace: fineract
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgB9jaH9ngefgHEmDv5ml+xfj/5GVLLmQr1mC4CcKpJHytJ/YtUHDYu21jR/V9hUGwU8Hi6O4N8jHN/W1hG+In8GHSYcxVm8T1qC0MDUr/EtPVVvdzdgsRp/WfEeE09QafLadnIPkoYJANk7u0FYEl4FDOMeu70gPO6/TVeP4T4cERUsyIH0YJZPOzQLH2p0yy8go2EjDzKvWAAo9/ofOBhKWFJbx8lD9dY/v84w7zMGSPERLkgMtq7jd3/03VX3lnxctcE17pCdJDbnf4pey2InsXb9OVpXQvOYnoVZMJ0z5wkUi1vXKw/tVw8R1meLALRfoasf7OOpEHmSetp0uLAfdX61nB43l8a0A3rjQwFlqMXEYE6ihrVbSCz2XkAWJt3OG7ZaY8r0ZpwlZ9drqcFNdNQAcyHKkcdY2aEPK4H/Cmviao5i9/gNPvgeJN7DXe/EO9Gg5wXSoGQ6o9qNvm/S3Me8K4E7qtrBtWQuLbOab658duKx+e5RNXOGxAimYEd+62QCao/s0aYNPNu7K64stnYGhteBpqDqPyQnlSp2LXr35hIOHS9HzGj8fIVha+OlJbVLq1nz2zKZb0qI5fAezQgMCp18hoPeP1KJ7+V+j685qxKkAunisz42pq+cd8kIBVSMDf21u1T0bbumtmVfgX3fodk7/02HiR89E6ioMkSbP/FMNLm+CIiSGZ2apI7/ShLPw9JNZWLzQ/xlt2W1sxMDNabOudBshSdY+csQqL0vNruXPEpckM94Qb2iwmc=
    keycloak-client-secret: AgCKvxehl0yL3ykHxdLeYdYW8dX1S+s2xpTC+njt/stB+5DdGYCRNu9YNmuKmXAqyzDpK3dBmref4htJHlCFhvEPHECPEGMpLAM3yphFlZtFxJvtOkP2jbBh5e2pIQers5UYxDjOFCFawwhG2PdEaVyAohC0MVKbrVdthJwgVbIJifak+cyRgsypp1w7cm9AlSVTiMnNCA8MmrxlYSFMPadKpxdpbCcRUtzdL3pSS3TshSaXa1C0Ea43qF7FVWgkQRN3cqPh5EgBr18Axln9jEO1/ZuSJKVRUSm/ZX6EWXAoYuamN9eQlTeYsyNI6fExk9I6f0JckHLm/bkMbbvPdJEkw+JJburDj0DdK14HCIMuCspWAyifyIyvIS6htq6HtpAiOafOFUo8WjlTtTN/IdrC8sV/z0c2u/CkR30x84482IMIqAT+gvIrMkRtx03zJxWdYLgrYs+0FVPP6Zc/KGOmggt3u1c/VvT4yZbWGPEZBc9ALrfjZxKhGyaNs3YC+YaxKuUepmKa257sDkfqGGovSCTLbxNQzBrVIMdfZz3JehZjAEv0/KIVQIB333U/13xWYKo0KL3DejIuTmMsKZkKqPhWvoj5ZF3M8sRqqnz3gbITo5rhKyomkL/Do5tE05IeqM/Wx6GEpFa9uPdM5UeMgvpmsOXBtKyVXuAfJlXQGXzv68VOUG+nD0/Gr5GnPCyxuGxb5aA9fH+G4yYxOtikrIM=
  template:
    metadata:
      creationTimestamp: null
      name: kyc-manager-credentials
      namespace: fineract
