---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kyc-manager-credentials
  namespace: fineract
spec:
  encryptedData:
    keycloak-client-secret: AgDd4ymzsXarShI/i9coFH5EfCUAF80+1Ze1X3e6ONZk7+kIocXDGxFJO0TvyUxGgW14ltjRjT5dcHp9zr+1CRSxBn1o4XItwNOezTihb7Gu699i4A5i59SPlhrrs9Bj1WwBzLo/NAOsGJtfUOxEChMmIsRA3dg5y4QI8qO5rnoDa7eNEG2MG41+J0RUUBISsRRllwKHeC/3uOjh6R1yPIvQgZ3CRSt59xBji+XwpG2D1lvDz6KWZ0vc/43e7qxgs5lVOdMm6078xWLcjYIHRbWTM4P4YgXi4BIGb8MPI5/YENsRhluwotPdQm7eOoD0YW8UjUeGTGzOOG9iZl2sp9LKfiy4FWOzUj0tjaEAGQUXWllJwHH20fvYQXH3e38YbDz8X+n+rxNwjEZtIEsbfT9caYNjx4gGKYzIXmBx9MNFuWyuZeUT7z5wZ4SWbP77y081qoQ+PKNwGaNJYxLIVO6xxJuBgNdpDxv3YjweaNtnNrYJvNaYUXP9Liy+kUtVURpXCpszDXP0AxHJhQ4fSNrcUw7a1Tzo7kvOkLRqLaabIKZ03+UBYNcPA4ith3aft28PLhmExu/+7R088/EPKD985Q7DhjPpAJPoXWdo5T0vgkdnZi0VExkOcsYAJDlWe7bmk3ugrqQpAGFbjaV+dlBDNXPzQVTgdi2KjcV11OTp2kHtBfCLH0wS/DOft5m+MKWRzU4vJMC9PhC2w2oB1n2Vu1o=
  template:
    metadata:
      creationTimestamp: null
      name: kyc-manager-credentials
      namespace: fineract
