---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: fineract
spec:
  encryptedData:
    client-secret: AgA+PurjgaX4IV4EyOOUIEbJKdx+0BvkosuwGrFCqEIWbuSQSrTJwyHJvULUVUwN7Ah8qULCio9B0P/iKwYQ0RyD2pT/wusHX3pZbhKqMjpo91yKMoI4kAvdS0WUw/iyX8jrvaHue3OSE3xaMTTlPgb9PO1GFCLOGKKmcv7K1vKESKO6AXXhKWRhqRyPaYUEfEtw47hsdQAoEc8g+IVKsUrAP1fA5DvCCvL6nHJIpGXc/leVsaOOVqzgmLa8m9IPvKKsR3kvKE3i0Oa5eOIlRoTMFwNqIMb8d9FO4P9fOvRBFq3JozGyEbYv2dEgQw+73qzb4juqD5vIVQUDCc7A/UQjHdRWBpKNRBw/UAnGBZsCZUHvY4kJgvCZUHZ23CcXOqo25iUXuPR8/L+sxQnkClDkOOvEPM6SJSDZN6/iaJuEfoSErCUdsi3O3uLFyBo+bS87DEBNob20pl3TBvDv5U5wmMfxonq78tegG08eIz5a1+Na3i4gOc0Xzf8cLWdLTu1pcv+uFaqPkuvHEhTx5pfMP+s8DM21Ld3GNGdOYns5qakpbECWTe8AhP627nXjf76aN2sswHQ3Xt9JIRv451ZdwPjqlh6sMuiAcH8lkKt6Ts9k9GgYK4/BZUcOS/mFmKpheme3hkVC8sHL68kbmfsN35dxGEBPakVfQxh1zpbbcMXeEGDZeyhbE0vwnNPd6v1lDKFiilugQ+nX+/XTeoTyxvK0
    cookieSecret: AgCvAN4KswoGW5S12a2Cu/jnPTLqg3P4PFktoiOSb4BY6Ksv/iERLO5cHVWydI3StOJ4EbS2p3BRu2uIeV6LT4FzQyQAorP3SZcMQOlfduLkGUlAuQ80LC7O30DO1DWX1TM4cwMNZNZ6zBFU0QzIO7gv3SV+TZuKc/Ca0UIKvJknZaKyUbCiQ2iqMQnlSgcyIQYUhhSl+hU0l0s5Ui0fzN0bLu7W7FTjnj7+nFh6pbDqYOJZfXZsonQuoiPitm30ByDWOLnLHk4K0xR7XXg6dX0cI9IYbXXNvFzXxx3bHFMiwReWWsVOlAN0EaEJCJSCfr2gKrp8YGGWMaKS6OiGV9/Fo5M5daohUWGPEf+hXAbTbCOlqfUugKiVNQvbjm/td+Y4OGcsy60EWz4wQ/a1NDHXVe0QHWuRJAU2GfADP793/3JMLhJdEoB/A1jHis/FlelQsn3v8JzUeOrKCxZr0w/kZYbpC8euXjpf4GG8QeUN0y5g3gF4UASM3Hxrd+y8960QLkdqTFHQB4rrjg2dBiDbYYPBu+PfiLbLPLz42TCGSdyp/i5ZUI+YvFIwztXFZB+VjeMteraHmumpG+A94FkHfZSJ7FD7n0zfAZCyUacfdzlicSvtuKS/STzEQWEPcvbp545LJ4eikgr7024JXZH/YTvdTI70nnBDujrCpE8d2u/XtUf/QeHVeFjTGxx7lT9ETYp71SvvzrDJjH4nXrt2rd5Z4RVYPFN2o2UuRSYThQ==
  template:
    metadata:
      name: oauth2-proxy-secrets
      namespace: fineract
