---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-secrets
  namespace: fineract
spec:
  encryptedData:
    client-secret: AgAXZiCNFvMtqjSYn5nycIBVou3iHor3E7qTrRBSqWu3UC6Kk7eOcVMuxTHl3GWncvISu4vUcebVvIcXlv0PnURI6ZKb4qrIxgGBCAJbQLtOm6PuGuTM5p0FpFssySnhDM/tbLIOAPCfrLAzqtCatHXwUV8t7fOEYeYwQl3CJf6nkElzudljhIHQ/CyFUlRXHF36hfoIGFfFFr+JSwc3Q0VhYCkVw6gEaftvyIDMPy1Xki0VJPcxk9VrtDUxmA8psIepkjlSrk1ySW+YeeuKVjUE14hRl9P+amYUBjBppFZz9v103+t+z2znvrFOUy5cQn9yHvrLv91qCBnYIpTK3y5bXCb73xcq3tYH4+3h2Pgdo5mFAD/TEneRV0nvFHX278qTHPxW4aOIWgqekRTQyOcf7GqaMkMfOBdobbjMnDMBCTb6nfcqeEjNcgET8dOU5k7GI81BkVPb/N+CIEefOnlcYcWUJGO+xs1069Iw1+spVOQ2TCswRNU25YvIy4oXOS1/eMaMcv6cO5V1GxbLyGxUkxt/YdVxukC2IXExTpOFt9aIYSNYQAf/V4q/HVodIWt7j90ckJP8DfIP7sGKZT7AQSZfpGtiKEpS6qF3AEGcRW2C1o3cqEixgHsCo8lwosN+4mvC7VpY6wiJ4e6JvfDrxs302edFvm5Fa/1lrKMqWUR16DxVXJ08qnzsAZUqhH0RF37OoPgTtkZXVNGCpUjBexS0
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy-secrets
      namespace: fineract
