---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-gateway-credentials
  namespace: fineract
spec:
  encryptedData:
    keycloak-client-secret: AgDjT+bVDCOsZzD2UWFN8EA03zxfFuUh7PmuNvpYP6Re5skocQbHF5uKvakvi0SVmZLnb/oH7pbg1Q6UNnMgNsiTDxz/RHL2XUwk5Rr8k4ruzyeWoOp0Bp3WoSfQjHFDS6bbQUz39w7OJ/3he6qiibQSGIXWPtHLA12PzamP6hQIILH1Hy1ZaRS61e3v7W6uhkY3rVAv/eHzDZ1xVZnxRerrocUfMjZDAavkvQm0xtMy3Ih/ozu4G34Dz3PTbExFO5D+IsUg6rZWIgLl5cWtWbc2Yawz3RFxMW1tmilrHk7HJzeDrGkJ0HN4Frm31eT8AEmMy7dR3jdOaA24Rr7DeeFqXqU7aWCptxuddEGtyJH6yy4qoYOx8VlCXFhrw6JXcGS0MMW1Ygsa54Fryv4L66440aN3q+RfZFyCceK5OYb5s6Smkcm8FvxEwA5bZZM7E5JIbTDnoxKNrBogCbgFELEsbWlKZGqcgRBvPY21WjCbosVvIzWdTr2VBdKUuGiVyWe6ReLLSLfUvXvrGK05ZIDco7Kjt4z2tgcrvyTpkXHPozUm5WZFJgV6gz3HuDWHKp1KQzJor3lHjsQdvQmwMxUrEjBz6e4kuOz71e9MTzOC+Jhb0G5PoUhQ8flZWuW+pDU9q1e8qIyc7wslveFaucNtSX+B6hLpt1mHHbRwkUd2eJGrdu2xuTiL7nrX1y10tdHWCcJqLMsITg2MJxcryCgC09cBEVHQ
  template:
    metadata:
      creationTimestamp: null
      name: payment-gateway-credentials
      namespace: fineract
