---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-sync-credentials
  namespace: fineract
spec:
  encryptedData:
    keycloak-client-secret: AgDFtCx501bfWLdQY7PSWEOp1eqtI254sw6r3x7uaCYWFIzK4SKF6eKfqq8E5Af6Z2SrGiApV2j5PW4Oars1mNA63bgFTSGNkYY/U/cYr5PXtVE1yYevkbaFNFUOKxFKKfndYBXirOWN5qX3aPAKB6fuhpGii2akgaINKsoplQv06Ok3hnY3nIrN8j27tXFO8vOikYpdwV2VGJRUU4KDktYRm5K0krw3+hfiV9cV9JKVhH6VI4ArZHhFMKixf2M31JRtaY6iwVuXKr1JArIXJznkLKBfQEl1Ypnd/d+4T6cqjIxUMdY0Q5SMCJ0SmGmCxShoUtU1KCwTQmg8Pba9WgdlOL4DpZPTp4Gekj000cLBpDnY6qf4J0M55BgWUFyNv5cJ6ePqPCJQYeo5mAER81GID5PsNVlLQIJKr5L12Sp/Fm/YGXX06gNvPV1DTDOT1sjRSkncSdZ+9bnWFbxtI1tP3Imkk4jAJWMLcgzizqUuCMV6asVWaGGAK9KnukjSGr3kww3hz6BlaHEYpfBKQI0AajVqNwQ7Qnf5EOXYPOHfYg+F9yHDRi1RwIEJkqFBSSacroKwiFEZ+KyPU8Arel1n5qGTJAyHMaA9kQ6R6T6yWET3kWelrvJxcLpkjuU4MJBg3P2wP1bfYk5rB89YLr9E/KQA5btT4ie1eJPOsmWvvm3m2HopxYM2oDcISJORo7U4HVLyBMeG5EegprcwD3vK
  template:
    metadata:
      creationTimestamp: null
      name: user-sync-credentials
      namespace: fineract
