---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-storage-credentials
  namespace: fineract
spec:
  encryptedData:
    KC_SIGNATURE_SECRET: AgBpecHevL2+2xWfeU/0xj8luPfAjimYKrKfQjbJktYb2gqv1v5MIt/nvKH0XvNK1kZTbyW+QaegKSfKTlZO4VNSJIpKIS/EdC//vdq+P1bK+IZZrV4vEMRihXpNXOLdbWmzs8kh2zIeNsriYF4dFiXzdXRW4LjStQuNQELg4k3bpHgJjs8yv19fJbdMk+XtceRao33w2aZEHFEX4lP4XFRUWCIvEgXrbVvT+3yjHbnEuBvh+zqIZziXPw87/v6Bdvbg9i34es+r0ELkCklJs60lnHERPSLIZnKVK7Y2WYpIPtsVoUEaeZDIEY/LqUdNIaesv61C8y3dNw9NCRWmLymWqox4Gq/LzlFVHCHkDbSO1dbtop981WWp1efiMa+AuEtA98bluDdh4zDU0G3ICY0hqRONtARK8qEPoLP83donmgUvmF3MBW67MWpO2xR8NOeNBqIOyWWTMUtOcR4CelHE/4R4DITCOtPUJHTUWdqbIZSPnamYEaSNnDh/LCxNZZibYvFu/IV3GhuDuCzmbisv7dVA3onTEbMOP7vvPP5SX+kx0+DAPNcosQICaEQw3zrxFCXaQhkwXy5TeG4IuUpbs/KErlzyb5iOZXCM63e2HqKxeeIHXd+I2lv3AuzYFsMTyR5KGj88BbDeFUz7uQte3KoJqr5ZdNQgb9YdL7CkCmRlRFzy8rUjyr0fO0LqPVzT3TqVze7+rOWv5V75zV8vWJhEdwasgi/Dtkz+HRQRJb+cDQfZcrIzEbxASQ==
    USER_STORAGE_DB_PASSWORD: AgBYzgSLk9JGMYFeMOLsH1p8vRXiezbUsSo7JmUyu+M8CbW04wCHQJLiI5DrsjSduwkIKkI53dhKbX0nj3tZ12tQy+4frGPISfosHreduim9qsuZCsIlVmszL42dKcDZdNS9G6SPYAtKrGHYuXIjvGw8u66ms2Cc1MufMd2hFkh0CRiMWKQ6sStEvVU/lGKgK3BI+F7J3WhR3x6F5DHf6R6yi2GdYgwdxwwuG0sPLQbSOy0mLILgKsFoQwBwWmQXZM121R15UZuTlQHQ2GdvDroUzn8HJOn6Ds/KDXBlnqOsXT2+efvzG6gzm1Qo0bg9L94+iJSWH0aReLj23LO3AY/2BX552GQrO4ZcxR1OVFiF37el1E//CBFv5iXCdc0+1LR27PsiqbJo4Q1ZcgscuRIm2eIPPR0b1N6cW4C2Qetd6SGEnbGBV0/A2egKT7zMHaRXMqN6ADA/fo8zFI9D16XP0KkcbAvsshB1utWmCyrkLs0NBEDAgnkhh7sTNDvaTxz3q8EBAu4mIZvqASbtol8SEou3M3oHkKOb62uzmacjYdj+tyVhVTXsbPFqfBFFIh4wYLPuYtqq8bWQfYIlAy1WCvfm8f5XHUTsGSyWbXTO8a7c024FRTeJhFXt9uqhqJkYVvpFI7MV6P9g720JOduGJs2gNAVMOp7tnq9zN2RHTs+q24CIpT737lgHcKroVE7V+Py2GsWc13B6fSvtadOqcxYAVSRPRnc+x4NUVnayBA==
  template:
    metadata:
      creationTimestamp: null
      name: user-storage-credentials
      namespace: fineract
