{{- if and (include "postgres.standaloneEnabled" .) (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ include "postgres.namespace" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ include "postgres.password" . | quote }}
  postgres-password: {{ include "postgres.postgresPassword" . | quote }}
  {{- if .Values.auth.replicationPassword }}
  replication-password: {{ .Values.auth.replicationPassword | quote }}
  {{- end }}
  {{- range $index, $db := .Values.additionalDatabases }}
  {{ $db.name }}-username: {{ $db.user | default $db.name | quote }}
  {{ $db.name }}-password: {{ $db.password | default (randAlphaNum 16) | quote }}
  {{- end }}
{{- end }}
