{{- if (include "postgres.standaloneEnabled" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ include "postgres.namespace" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
{{- end }}
