{{- if and .Values.keycloak.enabled (eq .Values.secrets.mode "generate") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  KEYCLOAK_DB_USER: {{ .Values.postgres.keycloak.user | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.postgres.keycloak.password | quote }}
{{- end }}
