{{- if and (include "minio.standaloneEnabled" .) (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ include "minio.namespace" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  root-user: {{ .Values.auth.rootUser | quote }}
  root-password: {{ include "minio.rootPassword" . | quote }}
{{- end }}
