---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fineract-config-credentials
  namespace: fineract
spec:
  encryptedData:
    keycloak-client-secret: AgBQaKGbFSRJrSTMzA2yrNQ3iUjIk2cIPhGg56wfqORHZsFj8iEUqc9iG9Cjsbw5T2nH/dRI6TywBIJgN65ryebg2aFe8fyC2gE8230/0lS1z3NFc8xGQNxboewhRegI3jP4MromPZvVsH1+WCGWc8iLE6k92a2KYlNVxixWKdy//mjDAjLtvinp+UNG/bpzzMj6SLyi0S22+/FtclXmK9YavtzYkzNM7aMPvPUNiyVYeJO7r/qbQm07CqXo+P+am2q7Kk5QORHI6Jk/JBMrrthcdCH6ZQlqXJYto3NA1ZFD0uEIvn8uYdtOx37Y8SxlzjLPfXj7vC+c1xJSFZlGYLLnPa5xMdQbYBy0Jq+yR4IXkAMvoU51gxcZ8vyETPfizs7YwsQhViYs83NE+P1x08CSA8EQATr9a98V+Ox02y9x1rrc61CPWcAx6BINdL4n2ttRnYWc4kPX6brD3bVVGtI12Q0Vho9LJLObfLaHQXxa72txm6eZHd47xvJrAP533f854EcL2jh39saUzgxPtYt3NCBx3wH1REY3X9Ad2ICXxzslbfqFwty8CPT7xaEaAej3d0gvoHuaocD+NvoUS+qJ/N4ZdEuskTxsuwQLlQ1C/pN0vc9i8cFVeaByRihdAjdLbNKehsSFC3Ez4cUQpK6JjZlSpt/RF92+L/2LuJiX0VB9R9fJmuGoqF3LDSE512l/UmI8OHCDlq3UW2tJEm9r4WMM4gpN
    oauth2-client-secret: AgA2J+YfgRXvwIISq3WTo058IXVq/YWM9LA3DU5p2ot9rUDZ/i0KDx6Oyc7Sy3oiNjUL7Q/U9xlxF7Dm0vI4PEczYKrAU2yXF8SSwQKHHbOYORYrbTAWuZOXcRPLmfz++2hvyZgJSB4VypkVKfscxvLld1mXnuGEbS3eveFKM7oxojHQEyJdQXxC+vwtwUT+eVCK0Mxb2DQ38GQuWp85+YFzJWmZjQ8EA9KchmvVUcOCSfK0wiWYf0w2cbEVSFQe+xUam/qHR5025TOudtritQjDhvui+2cghtFvyN35o5Lzklh2WOrYL4RQeG5yQ4VyQJfBOpceLZUx2oFsa1Va0cB/tiGdhZusExfbZJhk80DbzziJRdc4JJyu7pdY9HJBZAkKPMpfHhxqAvLn4hnK1ia1dVsWvJVB5qegxJaheatArGD6zB15Jr/diIA9MXr0UgbFwKsKIZCBeLlUB5IMAnr1AwGCUnjo2bigFCn7yQ6bDjX4OReM0P7hLbM7yJZKFBiyWyPjdcXsmnxvzRox44Ays/CLSV5CJZpfmZjHo63KXR93nXwtb4JwkzZgVmGHF0p7+dsvZf3u9mx+xN790eLgqtsg6YTAwlYkwHTDPg2y8X8F+i04tchh4Dawl8DpMnPP4eEcyz11qnVXfNGARuUPWbcZdFlBgaeEHCSwSMBI20WMaQ3qirMHl3OwEguXcglGUTciRVZ1vRUKwqAF4KWNpXiwa8eB
  template:
    metadata:
      creationTimestamp: null
      name: fineract-config-credentials
      namespace: fineract
