---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infra-cache-redis-auth
  namespace: fineract
spec:
  encryptedData:
    redis-password: AgAIvW0T2Ju8X2/zZYGAYWPDt62R17aip2JtdzuMPCucpDjlwv+lLL5ejOjBYnJ1t86jToWr/PaO4nxTbOmx3I/y+kKuU7K7DjTfFuGKH+lO26FGcNVuGchjGYc9HWImsv25Z6R5C8hCWPYQVwCNuqHul8shfXO3Lcqwn0BQTi5+GVxr2zzk9zle4iagVqWMbeYrIPBubOnoc3BXLiyWVUTL9tow4kSEPqolvhsRzunaLCHZtlU9mRnB7u+0OcC829NTZVmVa81+OoibCzClnytnDsGyMTx6F1xKm8hNUXPhhF5AV36E7Ct3RsJTLfVFYnkTtZtJkSbZv8VFbJNLUmgS5e8JulTa8e9Sy743I/U4QVKKcDrKIWmTW7deFH5/PQpRPGUHwMsO9Tdy+fcB3Qw8J7T7G2S6nfdt8tUcJ2PrDgrqtO+yO/KsMu6GlJdz0LKQHLng2inek0EaiiT36KSsDBaw3TnQjXlmxdNywZo6Gty2uyoHXSfzgKnbfabr1dzAlLtanSv1oJqmGhx9AlvkKG4RPHDY2L9a1ZURaLk2vYHtL+39KtdBC5WV7i/YQFMMc8CWFs7zeqP4ttnk2e9XTH+X62gab3Cc6CbGcILzJDtOv9PgxuqOSuynNl4VH6YUW7sjBolSrXuqrOIcpkvoOLo0VyRQ2KYE5raSXl0SIrrJo91L100nnQuZzwz44+ahDLlgxqDFzKb/WP+LMsWjfJ4=
  template:
    metadata:
      creationTimestamp: null
      name: infra-cache-redis-auth
      namespace: fineract
    type: Opaque
