---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infra-cache-redis-auth
  namespace: fineract
spec:
  encryptedData:
    redis-password: AgC6TRbtvgwCgE3tKyZNgs9FZVeQanzZ8De27SNEmLDjCzm8Nqd/+B/6cEP+kuwaeAc1PSSJ3iXplak/pu6SZNrmoWQbvgpTiz4ZPD83ktzU1nrPD6yqainNImR7kawtVWOC0PsiauZIAg6DY8HvlqQmPrtNKN/Sjfr7Ve49NJoIj1RGWx7c/5fuTSUS2eaIKKa98PIXvk13WWD3babGFTgdyLBp/A5uy7p6zSM/Hh0L1OWCGeEmSfEsNCwo7Fv2w5/WZwKG6oLOsG4JIZqJL9v7DJay7RVl5XiXLErWSfOSVItVKzvbV2czgeU8LUgd+TNI/65tV5B78xJ2bGXeGICeqpq1Lr9NN4O31CLwOAgGuZ1UEGW9Ib1z+kUsIRB4UKuwX+nQ1Fx4L9gVIDIAlYvGK6RFCuJI/Yk9rvqHByfFHEYLthAYswiiIUJEVMxiTUAneZDA/lf9FCeDfdrJf5ke8Or/4wse4rJ5hqPPBrFuPf0IZbwI2yuziprhVu2MRKkLKw5fAuD74TiT0d3WVqx0pxdRapWpMR1wZRMmIsXiHgttlVTDP7MWLUUgJ+gZpx6RXnEKff8ZpXZRYaiMs3+eYyUAUEA8pRTmONwS0Ozz5ax34+AozV8kOuckqkOnZ87eRLcWCE4bzCY0rcWPJ+a20dCyC/mXkWN2RLCfDCv/YvP4qmpUOdY3Q+W7v+o55llw85OFkIxZtYTh9YwzfRGjnTSZoL4=
  template:
    metadata:
      creationTimestamp: null
      name: infra-cache-redis-auth
      namespace: fineract
