---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgres
  namespace: fineract
spec:
  encryptedData:
    KEYCLOAK_DB_PASSWORD: AgBv+1qn6F728hp21SJoj6VMREKMQ/HcafrkU9x8xa+DAseBkMtgBmfPzXlxq3DG/5PwCUC2KhsmP4ffMerx8+jxoQMJtnxCV85Zuz9cgvRfwdMh0LxU+KrQfLN9TID1UXQfTg7ByqAcwymJzMnIlixly8u1d3YQIppo/3J/gWaohtEAYPC5/3HIiqLPvlsYcTui5MagDaPowMlsFg6BU1T4vZo38GtBodbJvvufjQkPtsyJUKYr1qnLwFHvCoqXzx03zLXMh7hb7Ua911ixPjYbgMTjrkPNPSADkh6NC+pM70jpGFlt0bw30lN21fQ7WfMJwuU5Ky0BP3eacCsftEq3B9jcYZ3J5yfjctWOOpE8VXdlCxwak2hCsQyuBlu1Lp9vstglh4SeyQFVfsdbP+lcRNowjdsdDIf012ZdRUMkZfnUemb3dxga26Cs8ca8Po/zYeWB1zfg720UeYmHMt4Q56k9HuvrSWzR45neesap5ATndiFFjvDaP06d2rB0RmuwtP7zA/hyYT5Jc49BHXASyURAUuaeoUO1FXuQve2wtBNIuhf6WQ3SVx2sNkAiIhSe7CJnnWohJGnDnjuF6jJgXeAMQUjdw8yYF/NcngtrenXBZjuV9xbXoXT/xAqqFFGtKnlrrR/yAhG3m8VNxlUWp4YlmETbIshmDaWkiMkLaQNFTDcP6IP675UdexBRdUMnc+KXFSv8bn3HKh8vBMzMFQ==
    KEYCLOAK_DB_USER: AgAPka1iU+//OvtxMdGUOYC3WD974gah230re7F3aqp7fpBjl4JU8dmvKn4s2mf9KctDlEtvcnEJqr9A5KfguAA5XupV66kt2Z4807jtUU2uFXUf5aLjt7ls/+OdsGb1xKKqj1OKJo7XxsUiFtbzCaINMkuPxe9dLx4FBVUOKSCQXEY+uNINZ4aJCob3nBLmhYO3ndpbsDPEWOSkQdXz3Z8jjzRgwEqqzoVLOkqqTuD4mUxXQFQiOEbgfoV5VTJpbJuCvEuYZ+X1W0NWDs96jw73oKe8O0zrTK8ZDpwOfa4xf96C29yW3mJfRtwtfwxlm1UuE1xALzJLb8ObZOUw/y6WX9bMRYCJr2gsDDBVNCgpDhlNNK6ZjNImf7xFWj4/f8CpgCb1Ehqsf57JRjw8whpGsVBsZAtuDvpw0FmVheZMMP1r7IyrpiCbsMiO3PldLTlLRz1IdK/9/SEjynFPnsby4oz36XjuIdd7q679u8jBC+knWnNART7Fq3iBhZwm2GTvgh+MQRysn3jNEyRe2Jp5hL2wDYoU20f2a32nr7n88dinklXV/T3zTJm0j7P62YiEpXNW/H/s8uowN1FSs30ZAa06TdHyLBhutaEExD3TXOcLuEvxOYq9zH2gBgenFNxzGXRUrJZxa5FtaiVkxdnExZzuAph1DTFwrWADvmqvs+wum/+XZUr/NcxsirmtqmpL8v69h6yAxw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgres
      namespace: fineract
      labels:
        app.kubernetes.io/managed-by: Helm
      annotations:
        meta.helm.sh/release-name: keycloak
        meta.helm.sh/release-namespace: fineract
    type: Opaque
