apiVersion: v1
kind: ConfigMap
metadata:
  name: azamra-ui-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: azamra-frontend-mobile
    {{- include "azamra-ui.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "backendUrl": {{ .Values.config.backendUrl | quote }},
      "powDifficulty": {{ .Values.config.powDifficulty | quote }},
      {{- if .Values.config.otlpEndpoint }}
      "otlpEndpoint": {{ .Values.config.otlpEndpoint | quote }},
      {{- end }}
      "keycloak": {
        "realm": {{ .Values.config.keycloak.realm | quote }},
        "kcUrl": {{ .Values.config.keycloak.kcUrl | quote }},
        "issuer": {{ .Values.config.keycloak.issuer | quote }},
        "clientId": {{ .Values.config.keycloak.clientId | quote }},
        "scheme": {{ .Values.config.keycloak.scheme | quote }}
      }
    }
