{{- if .Values.networkPolicies.enabled }}
# Allow traffic to azamra-frontend-mobile from ingress-nginx only
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-azamra-frontend-mobile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azamra-ui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: azamra-frontend-mobile
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.port }}
{{- end }}
