apiVersion: v1
kind: Service
metadata:
  name: azamra-frontend-mobile
  namespace: {{ .Release.Namespace }}
  labels:
    app: azamra-frontend-mobile
    {{- include "azamra-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    app: azamra-frontend-mobile
